#!/bin/sh

set -eu

: "${RELEASE_TAG:?RELEASE_TAG is required}"
: "${TARGET_ARCHITECTURE:?TARGET_ARCHITECTURE is required}"
: "${SOURCE_DIR:?SOURCE_DIR is required}"
: "${PACKAGING_DIR:?PACKAGING_DIR is required}"
: "${ARTIFACT_DIR:?ARTIFACT_DIR is required}"

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    autoconf automake build-essential debhelper dh-autoreconf dpkg-dev \
    heimdal-dev libtool pkg-config

test -f "$SOURCE_DIR/configure.ac"
test -d "$PACKAGING_DIR/debian"
rm -rf "$SOURCE_DIR/debian"
cp -a "$PACKAGING_DIR/debian" "$SOURCE_DIR/debian"

cd "$SOURCE_DIR"
version=$(sed -n 's/^AC_INIT(\[knc\], \[\([^]]*\)\].*/\1/p' configure.ac)
test "${RELEASE_TAG#v}" = "$version"
test "$version" = "$(dpkg-parsechangelog -SVersion | sed 's/-[^-]*$//')"
test "$(dpkg --print-architecture)" = "$TARGET_ARCHITECTURE"
dpkg-checkbuilddeps

DEB_BUILD_OPTIONS="parallel=$(nproc)" \
    dpkg-buildpackage --build=binary --no-sign

mkdir -p "$ARTIFACT_DIR"
cp ../*.deb "$ARTIFACT_DIR/"
